name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Use qodana-backend config'
        run: cp qodana-backend.yaml qodana.yaml
      - name: 'Qodana Backend'
        uses: JetBrains/qodana-action@v2023.1.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

  qodana-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Use qodana-frontend config'
        run: cp qodana-frontend.yaml qodana.yaml
      - name: 'Qodana Frontend'
        uses: JetBrains/qodana-action@v2023.1.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}